# Generated by Django 4.2.1 on 2024-08-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_deleted_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag'),
        ),
    ]
