# Generated by Django 4.2.1 on 2024-09-05 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_parcela_installment_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.conta'),
        ),
    ]
